# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
#   'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# -------------------------------------
# Site Settings
# -------------------------------------
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title  }}, {{ site.email  }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable  }}.

name: Chetan Malhotra (student developer for CERN-HSF) 
title: GSOC Devlog
description: Tracking progress on 'Visualization tools for Scikit-HEP project'

gh_name: debuggermalhotra
gh_commits: https://github.com/histogrammar/histogrammar-python/commits/?author=debuggermalhotra
gh_prs: https://github.com/histogrammar/histogrammar-python/pulls?utf8=%E2%9C%93&q=is:pr+author:debuggermalhotra
gh_issues: https://github.com/histogrammar/histogrammar-python/issues?utf8=%E2%9C%93&q=is:issue+author:debuggermalhotra
gh_project: https://github.com/histogrammar/histogrammar-python

# -------------------------------------
# Build Settings
# -------------------------------------
markdown: kramdown
future: true
encodig: utf-8
highlighter: rouge
